language: node_js
node_js:
  - "6"
env:
  - CXX=g++-7
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-7
branches:
  only:
  - master
  - development
install:
  - npm install
