# =============================================
# CONFIG
# =============================================

# site
root:             /
dest:             <%= site.root %>

# assemble
templates:         site/templates
layouts:           <%= site.templates %>/layouts
layout:            default
pages:             <%= site.templates %>/pages
includes:          <%= site.templates %>/{includes,pages}

# assets
css:               <%= site.root %>css/
imgdir:            <%= site.root %>img/
js:                <%= site.root %>js/src/
jslib:             <%= site.root %>js/lib/
bower:             <%= site.root %>bower_components/


# =============================================
# METADATA
# =============================================

# site
title:              Transformicons
url:                http://transformicons.com
